disabled_rules:
  - force_cast
  - force_unwrapping
  - trailing_whitespace
  - vertical_whitespace
  - multiple_closures_with_trailing_closure
  - large_tuple
  - line_length
  
type_name:
  min_length: 3
  max_length: 40
  allowed_symbols: ["_"]
  
